### ISSUE TITLE
[ META ] General Refacto

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor#103]
- [ ] remove projectList and groupList to use ItemList Component
- [ ] implement agnostic selector component into ModalEditProject
- [ ] Remove ModalEditProject and ModalEditGroup to use MMUModalEdit
- [ ] Remove ProjectCard and GroupCard to use MMUCards
