### ISSUE TITLE
[ Meta ] All known crashing issues on MAE

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-annotation-editor#110]
This issue gather all the bug that caused crash on MAE

- [ ] https://github.com/SCENE-CE/mirador-annotation-editor/issues/46
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor/issues/61
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor/issues/96
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor/issues/108
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor/issues/109
