### ISSUE TITLE
[ Meta ] All known usability issues on MAE

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-annotation-editor#111]
This issue gather all the bug that caused crash on MAE

Debug component (top priority to know where to go)
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor/issues/50
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor/issues/71
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor/issues/77
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor/issues/78
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor/issues/82
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor/issues/86
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor/issues/90
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor-video/issues/3
- [ ] https://github.com/SCENE-CE/mirador-annotation-editor-video/issues/4
- [ ] #125
