### ISSUE TITLE
Package MAE for publication

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-annotation-editor#19]
Package MAE to share it 

- [x] Build without post_install
- [x] Config file for manifest sample 
- [x] Example data 
- [x] README
- [x] Package JSON 
- [x] Use M4 upstream instead MV
- [ ] DR do the communication stuff
