### ISSUE TITLE
UI Improvement from 11/03 meeting

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-annotation-editor#38]
In template editors :

- [x] Replace text `Infos` with `Note (displayed in left panel)`
- [x] In the Tag template add a Tag section with a simple text field and the spatial and temporal targets
- [x] In the Document template, replace text `Network` with  `Document`

- [x] Remove back button in edit annotation
- [x] Shape list, remove all field  
- [x] Trasnform shape list
   - [x] On click on shape --> change current shape
   - [x] Transform accordion in list element 
   - [x] On one element --> type + trash button

**Comment by geourjoa** [comment]
No longer relevant
