### ISSUE TITLE
EPIC : UI / UX

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor#9]
NEW mockups for SCENE ALPHA : 

https://penpot.tetras-libre.fr/#/view/4271200e-514b-8106-8003-9cdaa4e24295?page-id=4271200e-514b-8106-8003-9cdaa4e2ab6d&section=interactions&index=0&share-id=45b8fe88-7525-810b-8003-adb32788b112&zoom=fit

- [ ] #10 
- [ ] #11
- [ ] #12

**Comment by Drilio** [comment]
if we want to overide mirador theme we should pass this code into config object in ./demo/src/index.js

``` 
 themes: {
    light: {
      palette : {
        type: 'light',
        primary:{
          main:'#506257'
        }
      },
      spacing:[0,4,8,12,16,20],
    }
  }
```

**Comment by daxid** [comment]
@Drilio here is the target for the template selection target.

![image](https://github.com/SCENE-CE/mirador-annotation-editor/assets/12066206/224bfb61-6c0d-4b45-8871-9a0aafa3003b)

The icons are all MUI. Please also mind the order.

**Comment by daxid** [comment]
In template editors :

- [ ] Replace text `Infos` with `Note (displayed in left panel)`
- [ ] In the Tag template add a Tag section with a simple text field and the spatial and temporal targets
- [ ] In the Document template, replace text `Network` with  `Document`
- [ ] Review the Overlay template with the team, several adjustments must be made

**Comment by geourjoa** [comment]
> In template editors :
> 
>     * [x]  Replace text `Infos` with `Note (displayed in left panel)`
> 
>     * [x]  In the Tag template add a Tag section with a simple text field and the spatial and temporal targets
> 
>     * [x]  In the Document template, replace text `Network` with  `Document`
> 
>     * [ ]  Review the Overlay template with the team, several adjustments must be made

Moved https://github.com/SCENE-CE/mirador-annotation-editor/issues/38
